function letcode=btc_vec2letcode(vec,dict)
% letcode=btc_vec2letcode(vec,dict) converts a vector of 10 correlations to a
% correlation structure with field names gamma, beta, theta, alpha
%
% vec: a 10-vector, typically a row
% dict:  dictionary of binary correlation names, generated by btc_define;
%    btc_define called if this field is empty
%
% letcode:  a structure with fields a, b, c, d, t, u, v, w, g
%
%    See also: BTC_DEFINE, BTC_CORRS2VEC, BTC_VEC2CORRS, BTC_LETCODE2VEC, GETP2X2_CORRS, GETCORRS_P2X2,
%      BTC_VECNAN2LETCODE.
%
if (nargin<2)
    dict=btc_define;
end
letcode=[];
for k=1:length(dict.codel)
%    letcode=setfield(letcode,dict.codel(k),vec(k));
    letcode.(dict.codel(k))=vec(k);
end
return
