function letcode=btc_vecnan2letcode(vec,dict)
% letcode=btc_vecnan2letcode(vec,dict) converts a vector of 10 correlations to a
% correlation structure with field names gamma, beta, theta, alpha
%
%  in contrast to btc_vec2letcode, here, if an element of vec is NaN, then
%    the corresponding field of letcode is not defined.  This is useful for
%    setting up calls to btc_augcoords, etc.
%
% vec: a 10-vector, typically a row
% dict:  dictionary of binary correlation names, generated by btc_define;
%    btc_define called if this field is empty
%
% letcode:  a structure with fields a, b, c, d, t, u, v, w, g
%
%    See also: BTC_DEFINE, BTC_LETCODE2VEC,BTC_VEC2LETCODE, BTC_AUGCOORDS, BTC_SOIDFG_MAKEX.
%
if (nargin<2)
    dict=btc_define;
end

lets=find(~isnan(vec));
letcode=struct();
for ilet_ptr=1:length(lets)
    let=dict.codel(lets(ilet_ptr));
    letcode.(let)=vec(lets(ilet_ptr));
end
return
