function stripped=btc_letcode_strip(letcode,dict)
% stripped=btc_letcode_strip(letcode,dict) strips a structure of letter codes
% of any fields that are NaN or empty
%
% letcode:  a structure with fields a, b, c, d, t, u, v, w, g
% dict:  dictionary of binary correlation names, generated by btc_define;
%    btc_define called if this field is empty
%
% stripped: a letter code structure, but only njmeric fields are present.
%
%    See also: BTC_DEFINE, BTC_TEST, BTC_LETCODE2VEC.
%
if (nargin<2)
    dict=btc_define;
end
stripped=[];
%new logic 21 Dec 2010 to avoid multiple calls to isfield
fns=fieldnames(letcode);
for fn=1:length(fns) 
    val=letcode.(fns{fn});
    if ~isempty(val) & ~isnan(val)
        stripped.(fns{fn})=val;
    end
end
%for k=1:length(dict.codel)
%    if isfield(letcode,dict.codel(k))
%%        val=getfield(letcode,dict.codel(k));
%        val=letcode.(dict.codel(k));
%        if ~isempty(val) & ~isnan(val)
%%            stripped=setfield(stripped,dict.codel(k),val);
%            stripped.(dict.codel(k))=val;
%        end
%    end
%end
if isempty(stripped) %so that stripped is a structure and has field names
    stripped=struct([]);
end
return
