function corrs=btc_vec2corrs(vec,dict)
% corrs=btc_vec2corrs(vec,dict) converts a vector of 10 correlations to a
% correlation structure with field names gamma, beta, theta, alpha
%
% vec: a 10-vector, typically a row
% dict:  dictionary of binary correlation names, generated by btc_define;
%    btc_define called if this field is empty
%
% corrs:  a structure with fields gamma, beta, theta, alpha.
%
%    See also: BTC_DEFINE, BTC_CORRS2VEC, BTC_VEC2LETCODE, BTC_LETCODE2VEC, GETP2X2_CORRS, GETCORRS_P2X2.
%
if (nargin<2)
    dict=btc_define;
end
corrs=[];
for n=1:length(dict.ordernames)
%    corrs=setfield(corrs,dict.ordernames{n},[]);
    corrs.(dict.ordernames{n})=[];
end
for k=1:length(dict.codel)
%    corrs=setfield(corrs,dict.name_order{k},{dict.posit(k)},vec(k));
    corrs.(dict.name_order{k})(1,dict.posit(k))=vec(k);
end
return
