function vec=btc_letcode2vec(letcode,dict)
% vec=btc_letcode2vec(letcode,dict) converts a structure of letter codes
% to a 10-vector of correlations.  Missing elements in letcode become NaN's
% in vec
%
% letcode:  a structure with fields a, b, c, d, t, u, v, w, g
% dict:  dictionary of binary correlation names, generated by btc_define;
%    btc_define called if this field is empty
%
% vec: a 10-vector, typically a row
%
%    See also: BTC_DEFINE, BTC_CORRS2VEC, BTC_VEC2CORRS, BTC_VEC2LETCODE, GETP2X2_CORRS, GETCORRS_P2X2.
%
if (nargin<2)
    dict=btc_define;
end
vec=repmat(NaN,1,length(dict.codel));
for k=1:length(dict.codel)
    if isfield(letcode,dict.codel(k))
        val=getfield(letcode,dict.codel(k));
        if ~isempty(val)
            vec(k)=val;
        end
    end
end
return
